function frases(opcao) {
  switch (opcao) {
    case 1: return 'O caminho é longo, mas a derrota é certa.';
    case 2: return 'Dias ruins se vão para que os piores possam vir.';
    case 3: return 'Comemore as pequenas derrotas, poderiam ser maiores ainda.';
    case 4: return 'Dica para a vida: Foco, força e fracasso.';
    case 5: return 'As vezes eu olho para algumas pessoas e penso: "Não é possível que esse era o espermatozóide mais esperto"...';
    case 6: return 'Não se arrependa dos seus erros, você ainda vai fazer muita merda.';
    case 7: return 'A vida é um conto de falhas.';
    case 8: return 'Procrastinar é necessário. Quem não faz nada, não erra e quem não erra, é promovido.';
    case 9: return 'Você não pode mudar o seu passado, mas pode estragar o seu futuro.';
    case 10: return 'Tem muita testa oleosa achando que é mente brilhante.';
    case 11: return 'Não se preocupe, nada vai dar certo.';
    case 12: return 'Relaxa, o pior está por vir.';
    case 13: return 'Não desanime com uma derrota, amanhã tem mais.';
    case 14: return 'Nenhum obstáculo é grante pra quem desiste.';
    case 15: return 'Se ainda não deu merda, é porque ainda não acabou.';
    case 16: return 'Tem os dias de luta e os dias de derrota.';
    case 17: return 'A maior derrota é tentar lutar.';
    case 18: return 'Lutando como nunca, perdendo como sempre.';
    case 19: return 'Se não puder fazer tudo, nem faça.';
    case 20: return 'No começo tava ruim, agora parece o começo.';
    case 21: return 'Se a caminhada está difícil, é porque você está no caminho errado.';
    case 22: return 'A expectativa é a mãe da merda.';
    case 23: return 'Quanto maior o seu esforço, maior será o seu fracaço.';
    case 24: return 'Você nunca será capaz.';
    case 25: return 'Parabéns, ficou uma bosta.';
    case 26: return 'Nunca permita que uma mensagem motivacional estupida alegre o seu dia de merda.';
    case 27: return 'Vai! Se der medo, volta.';
    case 28: return 'Nunca acredite no seu potencial.';
    case 29: return 'Você não falha quando erra, falha quando tenta.';
    case 30: return 'O problema não é a segunda-feira, é a sua vida.';
    case 31: return 'É preciso fechar os ciclos pra fracassar em algo novo.';
    case 32: return 'É sobre isso e está tudo uma merda.';
    case 33: return 'Não desista amanhã se você pode desistir hoje.';
    case 34: return 'Você ainda não chegou lá, mas olha o quanto já se lascou.';
    case 35: return 'Não espere nada de ninguém, muito menos de você.';
    case 36: return 'Nada como um novo trauma pra superar os antigos.';
    case 37: return 'Acorde cedo pra fracassar com calma.';
    case 38: return 'Calma, caramba! Vai piorar.';
    case 39: return 'Trabalhe com o que você ama e nunca mais vai amar nada.';
    case 40: return 'Pra ficar ruim tem que melhorar muito.';
    case 41: return 'Fracassar não é o fim. Recomece e fracasse até desistir.';
    case 42: return 'Quanto mais frases de superação você posta, mais a gente sabe que você não superou nada.';
    case 43: return 'Não pare até se humilhar.';
    case 44: return 'Nunca foi azar, sempre foi incompetência.';
    case 45: return 'Mais uma sexta-feira com "s" de sofrimento.';
    case 46: return 'Seu maior problema é você.';
    case 47: return 'Daqui pra frente é só pra trás.';
    case 48: return 'Tempos difíceis constroem pessoas sequeladas.';
    case 49: return 'As coisas ruins se vão para que as piores possam vir.';
    case 50: return 'Não existe caminho para o fracasso, o fracasso é o caminho.';
    case 51: return 'Tudo dando errado conforme o esperado.';
    case 52: return 'A vida é um portfólio de fracassos.';
    case 53: return 'Sonhar, acreditar e se lascar.';
    case 54: return '1º de Abril: Dia do coach.';
    case 55: return 'Haverá dias ruins e haverá dias péssimos.';
    case 56: return 'Nada como um dia pior que o outro.';
    case 57: return 'O dia é útil, mas você não.';
    case 58: return 'Nunca esqueça que você é limitado.';
    case 59: return 'Trabalhem enquanto eles herdam.';
    case 60: return 'Dentro de você está o poder de estragar não só a sua vida, mas a do outro também.';
    case 61: return 'Aquilo que te desafia, te transtorna.';
    case 62: return 'A vida não é uma caixinha de surpresas, é um container de decepções.';
    case 63: return 'Na dúvida: Abandone, desista e nem tente.';
    case 64: return 'O trabalho danifica o homem.';
    case 65: return 'Não é porque deu errado até agora, que vai dar certo daqui pra frente.';
    case 66: return 'Na vida é tudo ou nada. Tudo dando errado e nada dando certo.';
    case 67: return 'É errando que se aprende a errar.';
    case 68: return 'A maior motivação é o desespero.';
    case 69: return 'Se você pode sonhar, pode desistir.';
    case 70: return 'Você não é especial, muito menos vencedor.';
    case 71: return 'Sorrir pra não chorar.';
    case 72: return 'Quando disserem que não vai dar certo, acredite!';
    case 73: return 'Até o cheque é especial e você não.';
    case 74: return 'Não há saúde sem saúde mental.';
    case 75: return 'Foi só um dia ruim, amanhã será pior, descanse!';
    case 76: return 'Nunca fica mais difícil, é você que fica mais fraco.';
    case 77: return 'Se você trabalha pra pagar as contas, você é pobre.';
    case 78: return 'Veja pelo lado bom: todos os lados são ruins.';
    case 79: return 'Grandes derrotas exigem dedicação.';
    case 80: return 'A vida é um eterno nocaute no primeiro round.';
    case 81: return 'Reclame menos, fracasse mais...';
    case 82: return 'Cada passo pra frente, três passos pra trás.';
    case 83: return 'Nem tentar é melhor que desistir.';
    case 84: return 'Dias ruins constroem dias piores.';
    case 85: return 'Tudo certo, nada funcionando.';
    case 86: return 'Relaxa, tudo vai dar errado no tempo certo.';
    case 87: return '"Se qualquer merda entre aspas te motiva, tu é trouxa".';
    case 88: return 'O fundo do poço não é romântico, mas é profundo.';
    case 89: return 'https://instagram.fgru5-1.fna.fbcdn.net/v/t51.2885-15/205998172_246614686802079_2865726140360756860_n.jpg?stp=dst-jpg_e35&_nc_ht=instagram.fgru5-1.fna.fbcdn.net&_nc_cat=103&_nc_ohc=KUeDNRiuXokAX9BNzi4&edm=ALQROFkBAAAA&ccb=7-5&ig_cache_key=MjYwMjQ4NTE5NTY5NDYxODUxOA%3D%3D.2-ccb7-5&oh=00_AT_h5943kCup9FWkgGM-62UR-oaPioR3G22AAqfglBKwJA&oe=62FFD2DE&_nc_sid=30a2ef';
    case 90: return 'Se você está cansado de recomeçar, pare de tentar.';
    case 91: return 'A vida é feita de obstáculos e você tropeça em todos.';
    case 92: return 'Calma, você ainda tem muito a perder.';
    case 93: return 'Melhor sorrir de desespero do que chorar de alegria.';
    case 94: return 'Acredite, você não tem forças pra chegar onde quiser.';
    case 95: return 'Eu quero\nEu posso\nEu desisto.';
    case 96: return 'Não foi fácil, mas fracassei.';
    case 97: return 'Dos males o pior.';
    case 98: return 'Autoconfiança: O primeiro passo pra atingir o "me lasquei".';
    case 99: return 'De grão em grão a vaca vai pro brejo.';
    default: return 'Não importa pelo que você tá passando, amanhã sempre será um dia com um desafio maior ainda. Dito isso, você tem duas opções:\n\n1 - Aceita;\n2 - Escolha a opção 1.';
  }
}

module.exports = { frases };